[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "vs_degrade"
version = "1.2.0"
description = "Add randomizable Degradations/Compression Artifacts in VapourSynth."
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "pifroggi" }]
license = "MIT"
license-files = ["LICENSE"]

keywords = [
	"vapoursynth",
	"video",
	"degradation",
	"compression",
	"dataset",
	"dataset generation",
	"encoding"
]

classifiers = [
	"Programming Language :: Python :: 3",
	"Topic :: Multimedia :: Video"
]

dependencies = [
	"PyTurboJPEG",
	"numpy"
]

[project.urls]
Homepage = "https://github.com/pifroggi/vs_degrade"
Repository = "https://github.com/pifroggi/vs_degrade"
Issues = "https://github.com/pifroggi/vs_degrade/issues"
